smartlog: Abbreviate rewritten OIDs to 7 characters
arxanas/git-branchless pull request #701
Opened 2022-12-12 08:02 UTC by mlcui-google

This matches the default `core.abbrev` config setting.

I was confused as to why I couldn't find the rewritten commit in my smartlog, but it turns out there was one extra character at the end of the commit OID.

2022-12-13 21:39 UTC, arxanas requested changes

2022-12-14 07:00 UTC, mlcui-google commented on git-branchless-lib/src/core/node_descriptors.rs
> +                        // `7` is the default value for config setting `core.abbrev`.
(I'm a relative Rust newbie, so please bear with me if I can't find some methods)

`NodeObject::get_short_oid` specifically uses `Commit::get_short_oid`, which eventually uses `git2::object::Object::short_id` to get a short OID.

rewritten_oid is of type `MaybeZeroOid`, which is (assuming it's non-zero) is a `NonZeroOid`, internally a `git2::Oid`. Unfortunately, I don't think any these exposes a way of converting these into a `git2::object::Object`, unless there's a `TryInto` / `Into` / `From` impl that I can't see. Do you have any pointers?

2022-12-26 20:32 UTC, arxanas commented on git-branchless-lib/src/core/node_descriptors.rs
> +                        // `7` is the default value for config setting `core.abbrev`.
@mlcui-google The reason there's no `TryInto`/`Into`/`From` impl to convert `git2::Oid` into `git2::object::Object` is that it's not a simple conversion of data; the object must be read from disk, which requires another parameter. You would need to:

- Add a `repo: &Repo` parameter to `ObsolescenceExplanationDescriptor::new`.
- Move the logic in `ObsolescenceExplanationDescriptor::describe_node` (which calls `find_rewrite_target`) there.
- Use `Repo::find_commit` to look up the `Commit` objects and call `Commit::get_short_oid`.
  - For commits which can't be looked up (indicating that they've been garbage-collected) and for the zero OID, you should use the default behavior of slicing with `[..7]` instead. (Actually, we should first read the `core.abbrev` config setting, and only then default to `7` if it's not set, but that's not necessary for this PR.)
  - You may want to extract `NodeObject::get_short_oid` into a more general function which can also accept the zero OID, or do some other kind of refactoring.

2023-01-03 00:38 UTC, mlcui-google commented on git-branchless-lib/src/core/node_descriptors.rs
> +                        // `7` is the default value for config setting `core.abbrev`.
Thanks for the pointers! I'm currently a bit busy so I might not be able to get around to implementing this soon, so I'll move this PR to a draft state and come back to this later - hopefully within a few weeks.

2023-02-11 22:53 UTC, arxanas commented
Closing this PR for now since it's been inactive for a while. Feel free to re-open later.

2023-02-11 22:53 UTC, closed without merging